
-- Drop tables if they exist (in reverse order due to foreign key constraints)
DROP TABLE IF EXISTS stock_performance_metrics;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS daily_stock_data;
DROP TABLE IF EXISTS stock_symbols;

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_role_name (role_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default roles
INSERT INTO roles (role_name, display_name, description) VALUES
('free', 'Free Tier', 'Basic access with limited features'),
('pro', 'Pro', 'Full access to all trading analysis features'),
('enterprise', 'Enterprise', 'Advanced features with priority support'),
('admin', 'Admin', 'Full system administration access');

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255) NULL,
    verification_token_expires TIMESTAMP NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id),
    INDEX idx_email (email),
    INDEX idx_active (is_active),
    INDEX idx_role_id (role_id),
    INDEX idx_verification_token (verification_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create user_preferences table
CREATE TABLE IF NOT EXISTS user_preferences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    default_days INT DEFAULT 365,
    default_atr_period INT DEFAULT 14,
    default_atr_multiplier DECIMAL(3,1) DEFAULT 2.0,
    default_ma_type VARCHAR(10) DEFAULT 'ema',
    default_initial_capital DECIMAL(15,2) DEFAULT 100000.00,
    mean_reversion_threshold DECIMAL(5,2) DEFAULT 10.0,
    position_sizing_percentage DECIMAL(5,2) DEFAULT 5.0,
    trades_columns JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table 1: Stock Symbols/Tickers
CREATE TABLE IF NOT EXISTS stock_symbols (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    company_name VARCHAR(255),
    INDEX idx_symbol (symbol)
);

-- Table 2: Daily Stock Data (OHLCV)
CREATE TABLE IF NOT EXISTS daily_stock_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol_id INT NOT NULL,
    date DATE NOT NULL,
    open DECIMAL(10,2),
    high DECIMAL(10,2),
    low DECIMAL(10,2),
    close DECIMAL(10,2),
    volume BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol_id) REFERENCES stock_symbols(id) ON DELETE CASCADE,
    UNIQUE KEY unique_symbol_date (symbol_id, date),
    INDEX idx_symbol_id (symbol_id),
    INDEX idx_date (date),
    INDEX idx_symbol_date (symbol_id, date)
);

-- Table 3: Pre-computed Stock Performance Metrics
CREATE TABLE IF NOT EXISTS stock_performance_metrics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol_id INT NOT NULL,
    analysis_date DATE NOT NULL,
    total_return_pct DECIMAL(8,2),
    total_pnl DECIMAL(15,2),
    win_rate DECIMAL(5,2),
    total_trades INT,
    sharpe_ratio DECIMAL(8,2),
    analysis_params JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol_id) REFERENCES stock_symbols(id) ON DELETE CASCADE,
    UNIQUE KEY unique_symbol_analysis_date (symbol_id, analysis_date),
    INDEX idx_symbol_analysis_date (symbol_id, analysis_date),
    INDEX idx_analysis_date (analysis_date),
    INDEX idx_total_return (total_return_pct),
    INDEX idx_sharpe_ratio (sharpe_ratio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert stock symbols
INSERT IGNORE INTO stock_symbols (symbol, company_name) VALUES
('A', 'Agilent Technologies Inc.'),
('AA', 'Alcoa Corp.'),
('AAPL', 'Apple Inc.'),
('ACHR', 'Archer Aviation'),
('ACLS', 'Axcelis Technologies Inc.'),
('ADPT', 'Adaptive Biotechnologies Corporation'),
('ADT', 'ADT Inc.'),
('AEHR', 'Aehr Test Systems'),
('ALGM', 'Allegro Microsystems'),
('ALGT', 'Allegiant Travel Co.'),
('ALK', 'Alaska Air Group Inc'),
('ALLY', 'Ally Financial Inc'),
('AMGN', 'Amgen Inc.'),
('AMRC', 'Ameresco Inc.'),
('AMPX', 'Amprius Technologies Inc.'),
('AMZN', 'Amazon.com, Inc.'),
('APLD', 'Applied Digital Corp.'),
('APPN', 'Appian Corp'),
('AR', 'Antero Resources Corp'),
('ARKX', 'ARK Space Exploration & Innovation ETF'),
('ARMN', 'Aris Mining Corp.'),
('ASGN', 'ASGN Inc'),
('ASH', 'Ashland Inc'),
('ASPI', 'ASP Isotopes Inc.'),
('ATMU', 'Atmus Filtration Technologies Inc'),
('AXP', 'American Express Co.'),
('BA', 'The Boeing Co.'),
('BBIO', 'BridgeBio Pharma Inc.'),
('BBWI', 'Bath & Body Works Inc'),
('BHF', 'Brighthouse Financial Inc'),
('BKKT', 'Bakkt Holdings Inc.'),
('BKR', 'Baker Hughes Co'),
('BKSY', 'BlackSky Technology Inc.'),
('BL', 'BlackLine Inc'),
('BLKB', 'Blackbaud Inc.'),
('BMY', 'Bristol-Myers Squibb Co'),
('BRBR', 'Bellring Brands Inc'),
('BTM', 'Bitcoin Trust'),
('BWIN', 'The Baldwin Insurance Group Inc'),
('CARG', 'CarGurus Inc'),
('CART', 'Maplebear Inc'),
('CAT', 'Caterpillar Inc.'),
('CBRL', 'Cracker Barrel Old Country Store Inc'),
('CCL', 'Carnival Corp'),
('CE', 'Celanese Corp'),
('CGNX', 'Cognex Corp'),
('CHYM', 'Chime Financial Inc'),
('CIVI', 'Civitas Resources Inc'),
('CMG', 'Chipotle Mexican Grill'),
('CNM', 'Core & Main Inc'),
('CNXC', 'Concentrix Corp'),
('CORZ', 'Core Scientific Inc.'),
('CPS', 'Copper-Standard Holdings Inc.'),
('CRC', 'California Resources Corporation'),
('CRM', 'Salesforce, Inc.'),
('CSCO', 'Cisco Systems, Inc.'),
('CURI', 'CuriosityStream Inc.'),
('CVX', 'Chevron Corp.'),
('CZR', 'Caesars Entertainment Inc'),
('DAN', 'Dana Inc.'),
('DAR', 'Darling Ingredients Inc'),
('DFDV', 'DeFi Development Corp'),
('DIS', 'The Walt Disney Co.'),
('DKNG', 'DraftKings Inc'),
('DOMO', 'Domo Inc.'),
('ENPH', 'Enphase Energy Inc.'),
('EOSE', 'Eos Energy Enterprises Inc.'),
('ETHD', 'ProShares UltraShort Ether ETF'),
('EVLV', 'Evolv Technologies Holdings Inc.'),
('FCEL', 'FuelCell Energy Inc.'),
('FIVN', 'Five9 Inc.'),
('FLO', 'Flower Foods Corp.'),
('FSTR', 'L.B. Foster Company'),
('FTEK', 'Fuel Tech Inc.'),
('GOOGL', 'Alphabet Inc. Class A'),
('GPRK', 'GeoPark Ltd.'),
('GPRE', 'Green Plains Inc.'),
('GRND', 'Grindr Ltd.'),
('GRNT', 'Granite Ridge Resources Inc.'),
('GS', 'The Goldman Sachs Group, Inc.'),
('HD', 'The Home Depot, Inc.'),
('HDSN', 'Hudson Technologies Inc.'),
('HIMS', 'Hims & Hers Health Inc.'),
('HON', 'Honeywell International Inc.'),
('HTZ', 'Hertz Global Holdings Inc.'),
('HUSA', 'Houston American Energy Corp.'),
('HUT', 'Hut 8 Corp.'),
('IBM', 'International Business Machines Corp.'),
('IREN', 'IREN Limited.'),
('JBI', 'Janus International Group'),
('JNJ', 'Johnson & Johnson'),
('JOBY', 'Joby Aviation Inc.'),
('JPM', 'JPMorgan Chase & Co.'),
('KO', 'The Coca-Cola Co.'),
('KODK', 'Eastman Kodak Co.'),
('KOPN', 'Kopin Corp.'),
('KSS', 'Kohls Corp.'),
('KTOS', 'Kratos Defense & Security Solutions Inc.'),
('LTBR', 'Lightbridge Corp.'),
('LYFT', 'Lyft Inc.'),
('MAPS', 'WM Technology, Inc'),
('MARA', 'MARA Holdings, Inc'),
('MCD', 'McDonald''s Corp.'),
('METC', 'Ramaco Resources Inc.'),
('MGNI', 'Magnite Inc.'),
('MMM', '3M Co.'),
('MQ', 'Marqeta Inc.'),
('MRK', 'Merck & Co., Inc.'),
('MSFT', 'Microsoft Corp.'),
('NEXT', 'NextDecade Corp.'),
('NG', 'Novagold Resources Inc.'),
('NKE', 'Nike, Inc.'),
('NN', 'NextNav Inc.'),
('NPKI', 'NPK International Inc.'),
('NVDA', 'Nvidia Corporation'),
('NXT', 'Nextracker Inc.'),
('OM', 'Outset Medical Inc.'),
('PBYI', 'Puma Biotechnology Inc.'),
('PCT', 'PureCycle Technologies Inc.'),
('PDYN', 'Palladyne AI Corp.'),
('PG', 'The Procter & Gamble Co.'),
('PGEN', 'Precigen Inc.'),
('PINC', 'Premier, Inc'),
('PONY', 'Pony AI Inc.'),
('PPTA', 'Perpetua Resources Corp.'),
('PRCH', 'Porch Group Inc.'),
('QBTS', 'D-Wave Quantum Inc.'),
('QS', 'QuantumScape Corp.'),
('QUBT', 'Quantum Computing Inc.'),
('RGTI', 'Rigetti Computing Inc.'),
('RMBS', 'Rambus Inc.'),
('ROOX', 'Roblox Corp.'),
('ROW', 'Redwire Corp.'),
('RUN', 'Sunrun Inc.'),
('RXST', 'RxSight Inc.'),
('SATL', 'Satellogic Inc.'),
('SATS', 'EchoStar Corp.'),
('SERV', 'Serve Robotics Inc.'),
('SHAK', 'Shake Shack Inc.'),
('SHLS', 'Shoals Technologies Group, Inc.'),
('SHW', 'The Sherwin-Williams Company'),
('SLDB', 'GraniteShares 2x Long SMCI Daily ETF'),
('SMCL', 'Super Micro Computer Inc.'),
('SMST', 'Defiance Daily Target 2X short MSTR ETF'),
('SNDL', 'SNDL Inc.'),
('SOC', 'Sable Offshore Corp.'),
('SOFI', 'SoFi Technologies Inc.'),
('SRFM', 'Surf Air Mobility Inc.'),
('SSRM', 'SSR Mining Inc.'),
('STEM', 'Stem Inc.'),
('STNE', 'StoneCo Ltd.'),
('TRV', 'The Travelers Companies, Inc.'),
('TSLA', 'Tesla Inc.'),
('TSLL', 'Direxion Daily TSLA Bull 1.5X Shares'),
('TSSI', 'TSS Inc'),
('TTC', 'Toro Co.'),
('UEC', 'Uranium Energy Corp.'),
('UFPI', 'UFP Industries Inc.'),
('UMAC', 'Unusual Machines Inc.'),
('UNH', 'UnitedHealth Group Inc.'),
('URBN', 'Urban Outfitters Inc.'),
('USAR', 'USA Rare Earth Inc.'),
('UUUU', 'Energy Fuels Inc.'),
('V', 'Visa Inc.'),
('VG', 'Virgin Global Inc.'),
('VSCO', 'Victorias Secret & Co.'),
('VSAT', 'Viasat Inc.'),
('VTLE', 'Vital Energy Inc.'),
('VZ', 'Verizon Communications Inc.'),
('WMT', 'Walmart Inc.'),
('YEXT', 'Yext Inc.');